title: Alyssa Chen
authors: Alyssa Chen
url: "https://alyssachen.me"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About me"
   link: "/"
# - name: "Resume"
#   link: "resume.pdf"
 - name: "Research and Work"
   link: "research"
 - name: "Education"
   link: "education"
 - name: "Contact"
   link: "contact"
