title: Alyssa Chen
authors: Alyssa Chen
url: "https://alyssachen.me"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #
favicon_location: assets/favicon.ico

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "about me"
   link: ""
# - name: "Resume"
#   link: "resume.pdf"
 - name: "work and projects"
   link: "work"
 - name: "education"
   link: "education"
# - name: "blog"
#   link: "blog"
# - name: "contact"
#   link: "contact"

